# -*- coding: utf-8 -*-
"""text_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iHoXPOyhOMuNwjf_DQsLsTmtUpOAZWb3
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

text_df = pd.read_csv("plant_dataset_test.csv")
train_df = pd.read_csv("plant_dataset_train.csv")

print("Text CSV:")
print(text_df.head())

print("\nTrain CSV:")
print(train_df.head())

df = pd.read_csv("plant_dataset_text.csv")

import os
print(os.listdir())

import pandas as pd

df = pd.read_csv("plant_dataset_train.csv")

df.head()

print(df.columns)

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]','', text)
    return text

df["clean_text"] = df["text"].apply(clean_text)

df.head()

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["encoded_label"] = encoder.fit_transform(df["label"])

df.head()

!pip install transformers

from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

tokens = tokenizer(
    list(df["clean_text"]),
    padding=True,
    truncation=True,
    return_tensors="pt"
)

print(tokens)

df["label"].value_counts()

test_df = pd.read_csv("plant_dataset_test.csv")

test_df["clean_text"] = test_df["text"].apply(clean_text)

test_df["encoded_label"] = encoder.transform(test_df["label"])

from transformers import BertTokenizer

tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

train_tokens = tokenizer(
    list(train_df["clean_text"]),
    padding=True,
    truncation=True
)

test_tokens = tokenizer(
    list(test_df["clean_text"]),
    padding=True,
    truncation=True
)

import pandas as pd

train_df = pd.read_csv("plant_dataset_test.csv")

train_df.head()

print(train_df.columns)

import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]','', text)
    return text

train_df["clean_text"] = train_df["text"].apply(clean_text)

train_df.head()

test_df = pd.read_csv("plant_dataset_test.csv")

test_df["text"] = "This plant has " + test_df["label"] + " disease"

test_df["clean_text"] = test_df["text"].apply(clean_text)

test_df["encoded_label"] = encoder.transform(test_df["label"])

test_df.head()